# Generated by Django 5.0 on 2024-04-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='ContactUsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.TextField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Hero',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='', max_length=50)),
                ('course_title', models.CharField(default='', max_length=200)),
                ('institute', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='Software Engineer', max_length=100)),
                ('company', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=200)),
                ('title2', models.CharField(default='', max_length=200)),
                ('sub_title', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(default='', upload_to='logo')),
                ('favicon', models.ImageField(default='', upload_to='favicon')),
                ('hero_image', models.ImageField(upload_to='hero')),
                ('cv', models.FileField(default='Cv.pdf', upload_to='cv')),
                ('description', models.TextField(default='', max_length=500)),
                ('years_exp', models.IntegerField(default=1)),
                ('no_completed_proj', models.IntegerField(default=1)),
                ('no_clients', models.DecimalField(decimal_places=2, default=1, max_digits=1000000)),
            ],
            options={
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='PortfolioHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='', max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Hero',
            },
        ),
        migrations.CreateModel(
            name='ProjectPorfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ResumeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_title', models.CharField(default='', max_length=150)),
                ('edu_title', models.CharField(default='', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'ResumeHero',
            },
        ),
        migrations.CreateModel(
            name='ServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Service Hero',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_no', models.IntegerField(default='0')),
                ('service_title', models.CharField(default='', max_length=150)),
                ('service_desc', models.TextField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_img', models.ImageField(default='img.jpg', upload_to='skills-img')),
                ('rating_percentage', models.IntegerField(default=50)),
                ('skills_title', models.CharField(default='python', max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=350)),
            ],
            options={
                'verbose_name_plural': 'SkillsHero',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_img', models.ImageField(default='', upload_to='Porfolio-popUp-modal -image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('live_preview_link', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('client', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('project_desc', models.TextField(default='')),
                ('story', models.TextField(default='')),
                ('approach', models.TextField(default='')),
                ('next_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_project_rel', to='backend.portfoliopopup')),
                ('portfolio_item', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='popup', to='backend.portfolioitem')),
                ('previous_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_project_rel', to='backend.portfoliopopup')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Popups',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPopupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popup_images/')),
                ('popup', models.ManyToManyField(related_name='images', to='backend.portfoliopopup')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_img', models.ImageField(default='', upload_to='popUp modal')),
                ('description', models.TextField(default='', max_length=700)),
                ('process_descr', models.TextField(default='', max_length=400)),
                ('Process_list', models.CharField(blank=True, max_length=1000)),
                ('service_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.services')),
            ],
            options={
                'verbose_name_plural': 'Service Pop-Up',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projects')),
            ],
            options={
                'verbose_name_plural': 'Works',
            },
        ),
    ]
