# Generated by Django 5.0 on 2024-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(upload_to='testimonial')),
                ('role', models.CharField(default='', max_length=130)),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='TestimonialHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('desc', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Testimonial Hero',
            },
        ),
    ]
