# Generated by Django 5.0 on 2024-04-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_testimonial_testimonialhero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='desc',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='com_image',
            field=models.ImageField(default='', upload_to='testimonial_com_image'),
        ),
    ]
