# Generated by Django 5.0 on 2024-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aboutme_contactus_projectporfolio_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=200)),
                ('title2', models.CharField(default='', max_length=200)),
                ('sub_title', models.CharField(default='', max_length=100)),
                ('hero_image', models.ImageField(upload_to='hero/')),
                ('description', models.TextField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AlterField(
            model_name='projectporfolio',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
