# Generated by Django 5.0 on 2024-04-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aboutme_projects_cartegory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='cartegory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
