# Generated by Django 5.0 on 2024-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_desc_testimonial_quote_testimonial_com_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopopup',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apk'),
        ),
        migrations.AddField(
            model_name='portfoliopopup',
            name='short_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
