# Generated by Django 5.0 on 2024-04-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_hero_delete_aboutme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
