# Generated by Django 5.0 on 2024-04-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_aboutme_options_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='cartegory',
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projects')),
            ],
            options={
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.DeleteModel(
            name='Cartegory',
        ),
    ]
