# Generated by Django 5.0 on 2024-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_contactus_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='years_exp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='years_exp_text',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(upload_to='hero'),
        ),
    ]
