# Generated by Django 5.0 on 2024-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_hero_years_exp_hero_years_exp_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='years_exp_text',
        ),
        migrations.AddField(
            model_name='hero',
            name='no_clients',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='no_completed_proj',
            field=models.IntegerField(default=1),
        ),
    ]
