# Generated by Django 5.0 on 2024-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_hero_years_exp_text_hero_no_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='no_clients',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000000),
        ),
    ]
