# Generated by Django 5.0 on 2024-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_hero_no_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='cv',
            field=models.FileField(default='Cv.pdf', upload_to='cv'),
        ),
    ]
