# Generated by Django 5.0 on 2024-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_hero_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='favicon',
            field=models.ImageField(default='', upload_to='favicon'),
        ),
        migrations.AddField(
            model_name='hero',
            name='logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
    ]
