# Generated by Django 5.0 on 2024-04-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_servicehero_services_servicepopup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepopup',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='servicepopup',
            name='title',
        ),
    ]
