# Generated by Django 5.0 on 2024-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
    ]
