# Generated by Django 5.0 on 2024-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_contactushero_remove_contactus_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactushero',
            options={'verbose_name_plural': 'Contact Us Hero'},
        ),
        migrations.AlterModelOptions(
            name='servicehero',
            options={'verbose_name_plural': 'Service Hero'},
        ),
        migrations.AlterModelOptions(
            name='servicepopup',
            options={'verbose_name_plural': 'Service Pop-Up'},
        ),
        migrations.AddField(
            model_name='contactushero',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contactushero',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contactushero',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
