# Generated by Django 5.0 on 2024-04-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_contactushero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='', max_length=50)),
                ('course_title', models.CharField(default='', max_length=200)),
                ('institute', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='Software Engineer', max_length=100)),
                ('company', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='ResumeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_title', models.CharField(default='', max_length=150)),
                ('edu_title', models.CharField(default='', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'ResumeHero',
            },
        ),
    ]
