# Generated by Django 5.0 on 2024-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_education_experience_resumehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_img', models.ImageField(default='img.jpg', upload_to='skills-img')),
                ('rating_percentage', models.IntegerField(default=50)),
                ('skills_title', models.CharField(default='python', max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=350)),
            ],
            options={
                'verbose_name_plural': 'SkillsHero',
            },
        ),
    ]
