# Generated by Django 5.0 on 2024-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_skills_skillshero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='', max_length=350)),
            ],
            options={
                'verbose_name_plural': 'ProjectsHero',
            },
        ),
    ]
