# Generated by Django 5.0 on 2024-04-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_projectshero'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_gallery_images/')),
            ],
            options={
                'verbose_name_plural': 'GalleryImages',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=50)),
                ('client', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField()),
                ('designer', models.CharField(default='', max_length=100)),
                ('project_description', models.TextField(default='')),
                ('story', models.TextField(default='')),
                ('approach', models.TextField(default='')),
                ('gallery_images', models.ManyToManyField(related_name='popup', to='backend.galleryimage')),
            ],
            options={
                'verbose_name_plural': 'PortfolioPopups',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('uxui', 'UX/UI'), ('branding', 'Branding'), ('mobile-app', 'Mobile App'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('modal_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_item', to='backend.portfoliopopup')),
            ],
            options={
                'verbose_name_plural': 'PortfolioItems',
            },
        ),
    ]
