# Generated by Django 5.0 on 2024-04-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_galleryimage_portfoliopopup_portfolioitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsHero',
            new_name='PortfolioHero',
        ),
        migrations.AlterModelOptions(
            name='portfoliohero',
            options={'verbose_name_plural': 'PortfolioHero'},
        ),
    ]
