# Generated by Django 5.0 on 2024-04-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_projectshero_portfoliohero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='portfolio_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='backend.portfolioitem'),
        ),
    ]
