# Generated by Django 5.0 on 2024-04-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_galleryimage_portfolio_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='portfolio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='backend.portfolioitem'),
        ),
    ]
