# Generated by Django 5.0 on 2024-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_galleryimage_portfolio_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='portfolio_item',
        ),
        migrations.RemoveField(
            model_name='portfoliopopup',
            name='gallery_images',
        ),
        migrations.DeleteModel(
            name='PortfolioHero',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='modal_content',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.DeleteModel(
            name='PortfolioPopup',
        ),
    ]
