# Generated by Django 5.0 on 2024-04-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_galleryimage_portfolio_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='ResumeHero',
        ),
    ]
