# Generated by Django 5.0 on 2024-04-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_delete_education_delete_experience_delete_resumehero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='SkillsHero',
        ),
    ]
